import type {CSSProperties, ReactNode} from 'react';
import {interpolate, spring, useCurrentFrame, useVideoConfig} from 'remotion';
import {theme} from '../../theme';

export const clamp=(frame:number,start:number,end:number)=>interpolate(frame,[start,end],[0,1],{extrapolateLeft:'clamp',extrapolateRight:'clamp'});
export const FabricOpsLogo=({size=86,style}:{size?:number;style?:CSSProperties})=><div style={{fontSize:size,fontWeight:800,letterSpacing:-size*.055,color:'#f7f9fd',...style}}>Fabric<span style={{color:theme.production}}>Ops</span></div>;
export const SceneTitle=({children,kicker}:{children:ReactNode;kicker?:string})=><div style={{position:'absolute',left:110,top:76}}>{kicker&&<div style={{color:theme.production,fontSize:24,fontWeight:800,letterSpacing:3,marginBottom:14}}>{kicker}</div>}<div style={{fontSize:58,fontWeight:760,letterSpacing:-2}}>{children}</div></div>;

export const NotebookNode=({number,label,color=theme.engineering,style}:{number:string;label:string;color?:string;style?:CSSProperties})=><div style={{width:260,height:154,borderRadius:24,background:'#101e32',border:`2px solid ${color}99`,boxShadow:'0 24px 60px #0008',position:'relative',overflow:'hidden',...style}}><div style={{position:'absolute',inset:'0 auto 0 0',width:16,background:color}}/><div style={{padding:'28px 28px 0 42px',fontSize:34,fontWeight:850,color}}>{number}</div><div style={{padding:'8px 28px 0 42px',fontSize:27,fontWeight:700}}>{label}</div></div>;
export const WorkspacePanel=({title,color,children,style}:{title:string;color:string;children?:ReactNode;style?:CSSProperties})=><div style={{borderRadius:38,border:`2px solid ${color}88`,background:`linear-gradient(145deg,${color}20,#0b1729f2 48%)`,boxShadow:'0 30px 90px #0009',overflow:'hidden',...style}}><div style={{height:12,background:`linear-gradient(90deg,${color},transparent)`}}/><div style={{fontSize:34,fontWeight:760,padding:'28px 36px',color}}>{title}</div>{children}</div>;
export const Contract=({active=false,label='Data Contract',style}:{active?:boolean;label?:string;style?:CSSProperties})=>{const color=active?theme.production:theme.governance;return <div style={{width:270,height:190,padding:28,boxSizing:'border-box',borderRadius:26,border:`2px solid ${color}`,background:`linear-gradient(145deg,${color}30,#111c31)`,boxShadow:`0 25px 65px #0009,0 0 34px ${color}25`,...style}}><div style={{fontSize:21,letterSpacing:2,fontWeight:850,color}}>{active?'ACTIVATED':'GOVERNED'}</div><div style={{fontSize:31,fontWeight:760,marginTop:18}}>{label}</div><div style={{marginTop:22,height:8,width:170,borderRadius:8,background:color}}/></div>};
export const TableNode=({label='table_id',active=false,style}:{label?:string;active?:boolean;style?:CSSProperties})=>{const color=active?theme.production:theme.engineering;return <div style={{width:250,height:160,borderRadius:24,border:`2px solid ${color}99`,background:'#101d30',overflow:'hidden',boxShadow:'0 22px 55px #0008',...style}}><div style={{padding:'18px 24px',fontSize:28,fontWeight:760,color}}>{label}</div>{[0,1,2].map(i=><div key={i} style={{height:22,borderTop:'1px solid #ffffff16',background:i%2?`${color}10`:'transparent'}}/>)}</div>};
export const Rail=({progress,color=theme.production,style}:{progress:number;color?:string;style?:CSSProperties})=><div style={{height:8,borderRadius:8,background:'#2b3a4e',overflow:'hidden',...style}}><div style={{height:'100%',width:`${progress*100}%`,background:color,boxShadow:`0 0 24px ${color}`}}/></div>;
export const Enter=({delay=0,children,style}:{delay?:number;children:ReactNode;style?:CSSProperties})=>{const frame=useCurrentFrame();const {fps}=useVideoConfig();const p=spring({frame:frame-delay,fps,config:{damping:22,stiffness:90}});return <div style={{opacity:p,transform:`translateY(${(1-p)*42}px) scale(${.94+.06*p})`,...style}}>{children}</div>};
