"""Metadata registry for generated public API documentation."""

from __future__ import annotations

from typing import NotRequired, TypedDict


class PublicSymbolDocMetadata(TypedDict):
    """Documentation metadata for a public symbol exported in ``__all__``."""

    symbol_name: str
    module: str
    kind: str
    template_notebook: str
    template_segment: str
    workflow_step: NotRequired[int | str | None]  # Deprecated: retained for backward compatibility only.
    role: str
    purpose: NotRequired[str]
    summary_override: str | None






class ModuleDocMetadata(TypedDict):
    """Documentation metadata that drives module navigation and overview generation."""

    module_name: str
    visibility: str
    module_summary: str
    sidebar_group: str
    sidebar_include: bool


MODULE_DOCS_METADATA: list[ModuleDocMetadata] = [
    {"module_name": "config", "visibility": "public", "module_summary": "Owns environment setup, runtime initialization, paths, and notebook-wide configuration.", "sidebar_group": "0. Environment setup", "sidebar_include": True},
    {"module_name": "data_agreement", "visibility": "public", "module_summary": "Owns agreement metadata capture, audited record building, metadata commit helpers, and agreement selection helpers used to anchor notebook workflows to approved business agreements. Standard notebooks create or check agreement metadata tables in `00_env_config`, render agreement intake in `01_da_<agreement>`, and bind downstream work with `widget_select_agreement(...)` and `get_selected_agreement()`.", "sidebar_group": "1. Governance steward", "sidebar_include": True},
    {"module_name": "business_context", "visibility": "public", "module_summary": "Owns business meaning for tables and columns.", "sidebar_group": "1. Governance steward", "sidebar_include": True},
    {"module_name": "data_governance", "visibility": "public", "module_summary": "Owns sensitivity, PII, confidentiality, policy labels, and governance approval evidence.", "sidebar_group": "1. Governance steward", "sidebar_include": True},
    {"module_name": "data_profiling", "visibility": "public", "module_summary": "Owns deterministic profiling evidence such as schema, nulls, distincts, min/max, and optional lightweight distributions.", "sidebar_group": "2. Analyst / data scientist", "sidebar_include": True},
    {"module_name": "data_quality", "visibility": "public", "module_summary": "Owns DQ rule drafting, review, enforcement, quarantine, and quality results.", "sidebar_group": "2. Analyst / data scientist", "sidebar_include": True},
    {"module_name": "fabric_input_output", "visibility": "public", "module_summary": "Owns Fabric read/write helpers for Lakehouse, Warehouse, and file/table IO.", "sidebar_group": "3. Data engineer", "sidebar_include": True},
    {"module_name": "data_lineage", "visibility": "public", "module_summary": "Owns source-to-target lineage and transformation evidence.", "sidebar_group": "3. Data engineer", "sidebar_include": True},
    {"module_name": "drift", "visibility": "public", "module_summary": "Owns schema/profile/data drift checks as engineering guardrails during pipeline runs.", "sidebar_group": "3. Data engineer", "sidebar_include": True},
    {"module_name": "handover", "visibility": "public", "module_summary": "Owns final handover assembly and contract artifact rendering/export.", "sidebar_group": "4. Handover / data contract", "sidebar_include": True},
    {"module_name": "metadata", "visibility": "public", "module_summary": "Owns metadata evidence persistence, stable keys, notebook registry, and contract evidence loading.", "sidebar_group": "5. Metadata / contract store", "sidebar_include": True},
    {"module_name": "versioning", "visibility": "public", "module_summary": "Owns runtime package-version detection and documentation link helpers for Fabric notebooks.", "sidebar_group": "0. Environment setup", "sidebar_include": True},
    {"module_name": "ai", "visibility": "internal", "module_summary": "Internal AI utility surface used by workflow-facing public functions.", "sidebar_group": "Internal", "sidebar_include": False},
    {"module_name": "docs_metadata", "visibility": "internal", "module_summary": "Documentation generation metadata and flow mapping internals.", "sidebar_group": "Internal", "sidebar_include": False},
    {"module_name": "schemas", "visibility": "internal", "module_summary": "Internal schema artifacts used for validation and contracts.", "sidebar_group": "Internal", "sidebar_include": False},
    {"module_name": "_utils", "visibility": "internal", "module_summary": "Internal shared helper utilities.", "sidebar_group": "Internal", "sidebar_include": False},
]


class TemplateFlowSegmentMetadata(TypedDict):
    """Segment metadata for starter template guidance on the reference landing page."""

    title: str
    symbols: list[str]
    text: NotRequired[str]


class TemplateFlowDocMetadata(TypedDict):
    """Starter template metadata used to render the template-first function reference."""

    notebook_key: str
    notebook_label: str
    template_path: str
    segment_intro: str
    segments: list[TemplateFlowSegmentMetadata]


TEMPLATE_FLOW_DOCS: list[TemplateFlowDocMetadata] = [{'notebook_key': '00_env_config',
  'notebook_label': '`00_env_config`',
  'template_path': 'templates/notebooks/00_env_config.ipynb',
  'segment_intro': 'Shared environment bootstrap and validation before agreement intake, exploration, or pipeline notebooks run.',
  'segments': [{'title': 'Segment 1: Explain the shared environment role',
                'text': 'Describe what this shared config notebook sets up and what downstream exploration or pipeline notebooks depend '
                        'on.',
                'symbols': ['print_runtime_banner']},
               {'title': 'Segment 2: Define environment targets and notebook policy', 'symbols': ['FabricStore']},
               {'title': 'Segment 3: Set AI, agreement-intake, quality, governance, and lineage defaults',
                'text': 'The single `CONFIG` object exposes explicit `DataAgreementConfig` defaults for `01_da_<agreement>`. During environment bootstrap, `00_env_config` creates or checks `METADATA_DATA_AGREEMENT`, `METADATA_DATA_STEWARD`, and `METADATA_DATA_AGREEMENT_EVIDENCE` in the configured metadata lakehouse, then reports steward readiness. The editable widget config controls visible fields and JSON-backed custom fields. `01_da` can create steward rows first, then select active stewards while creating versioned agreements; no fake steward profiles are seeded.',
                'symbols': []},
               {'title': 'Segment 4: Assemble and validate framework config', 'symbols': []},
               {'title': 'Segment 5: Run startup checks and show resolved paths', 'symbols': ['setup_notebook']}]},
 {'notebook_key': '01_data_agreement',
  'notebook_label': '`01_da_<agreement>`',
  'template_path': 'templates/notebooks/01_da_agreement_template.ipynb',
  'segment_intro': 'Form notebook that supports two agreement-intake layouts for A/B testing. Option A renders a compact section switcher through `widget_render_agreement_intake_app(...)`. Option B renders separate widget cells for Data Steward, Data Agreement, and Agreement Evidence through `widget_render_data_steward(...)`, `widget_render_data_agreement(...)`, and `widget_render_agreement_evidence(...)`. Both layouts write append-only metadata and agreement intake selects active steward rows.',
  'segments': [{'title': 'Segment 1: Option A compact app',
                'text': 'FabricOps currently supports two `01_da` layouts. Option A is a compact section switcher via `widget_render_agreement_intake_app(...)`. Option B is separate widget cells for Data Steward, Data Agreement, and Agreement Evidence. Use Option B if Fabric output scrolling feels jumpy or if users prefer rerunning one section at a time. Do not run both options in the same notebook execution unless testing UX, because both render widgets for the same metadata tables.',
                'symbols': ['widget_render_agreement_intake_app']},
               {'title': 'Segment 2: Option B separate widgets',
                'text': 'Render separate Data Steward, Data Agreement, and Agreement Evidence cells with `widget_render_data_steward(...)`, `widget_render_data_agreement(...)`, and `widget_render_agreement_evidence(...)` when you want each section to be rerun independently.',
                'symbols': ['widget_render_data_steward', 'widget_render_data_agreement', 'widget_render_agreement_evidence']}]},
 {'notebook_key': '02_ex',
  'notebook_label': '`02_ex_<agreement>_<topic>`',
  'template_path': 'templates/notebooks/02_ex_agreement_topic.ipynb',
  'segment_intro': 'Exploration notebook flow used to profile source data and draft advisory AI outputs for human review.',
  'segments': [{'title': 'Segment 1: Load shared config and runtime', 'symbols': ['setup_notebook']},
               {'title': 'Segment 2: Profile source and capture evidence',
                'symbols': ['read_lakehouse_table', 'read_warehouse_table', 'profile_dataframe']},
               {'title': 'Segment 3: AI-assisted drafting (advisory only)',
                'symbols': ['draft_dq_rules', 'widget_review_dq_rules', 'write_dq_rules']},
               {'title': 'Segment 4: Human review and write approved DQ rules', 'symbols': ['write_dq_rules']},
               {'title': 'Optional lineage notes', 'symbols': []}]},
 {'notebook_key': '03_pc',
  'notebook_label': '`03_pc_<agreement>_<pipeline>`',
  'template_path': 'templates/notebooks/03_pc_agreement_pipeline_template.ipynb',
  'segment_intro': 'Core production pipeline flow for clean evidence creation, preset-driven source and target guardrails, inline runtime audit columns, large-table write tuning, and controlled publishing. 03_pc uses validate_schema, monitor_data_changes, and stop_if_failed so users choose intent while FabricOps handles profiling, baseline selection, comparison, and enforcement mechanics internally. Audit columns are always useful; hashes, datetime features, and bucket columns are specialized patterns outside the default path.',
  'segments': [{'title': 'Segment 1: Runtime setup, parameters, agreement selection, and registration',
                'symbols': ['setup_notebook', 'widget_select_agreement', 'get_selected_agreement', 'current_notebook_active_registrations']},
               {'title': 'Segment 2: Read source data',
                'symbols': ['read_lakehouse_table', 'read_warehouse_table', 'read_lakehouse_csv', 'read_lakehouse_parquet', 'validate_schema', 'monitor_data_changes', 'stop_if_failed']},
               {'title': 'Segment 3: Write reusable catalogue evidence from monitored profiles',
                'symbols': ['write_lakehouse_table']},
               {'title': 'Segment 4: Transform, add runtime audit columns, and publish outputs',
                'symbols': ['validate_schema', 'monitor_data_changes', 'stop_if_failed', 'build_runtime_audit_fields', 'write_lakehouse_table', 'write_warehouse_table']},
               {'title': 'Segment 5: Read back output and write lineage',
                'symbols': ['read_lakehouse_table', 'read_warehouse_table', 'build_lineage_records', 'write_lakehouse_table']}]}]

WORKFLOW_STEP_DOCS: list[dict[str, int | str]] = [
    {"number": 1, "slug": "step-01-governance-context", "title": "Governance context", "subtext": "This step captures the governance context: approved usage, owner, and data agreement. The agreement may live outside Fabric, such as in SharePoint documents. Functions in this step mainly link notebooks back to that agreement so the technical work stays tied to the approved business context."},
    {"number": "2A", "slug": "step-02a-shared-runtime-config", "title": "Create shared runtime config", "subtext": "This step creates the shared config that other notebooks depend on, including environment paths, workspace targets, AI availability, and standard naming rules. The goal is to define the project setup once so exploration and pipeline notebooks do not repeat hidden manual configuration."},
    {"number": "2B", "slug": "step-02b-notebook-startup-checks", "title": "Run notebook startup checks", "subtext": "This step runs the startup utility or smoke test at the beginning of every exploration and pipeline notebook. The goal is to confirm the notebook is running in the expected environment, follows naming rules, and has the required Fabric or AI capabilities before any data work begins."},
    {"number": 3, "slug": "step-03-source-contract-ingestion-pattern", "title": "Define source metadata & ingestion pattern", "subtext": "This step defines source metadata expectations between the upstream source and this notebook. It captures what data is expected, including schema, data types, update frequency, update method, watermark column, and whether the source is append only, overwritten, or slowly changing. Functions in this step help the pipeline decide how to ingest, validate, snapshot, or incrementally process source data using approved metadata tables."},
    {"number": 4, "slug": "step-04-ingest-profile-store", "title": "Ingest, profile & store source data", "subtext": "This step brings the source data into the framework, profiles it, and stores it for later use. Functions in this step focus on reading the data, capturing basic profiling results, and saving the raw or source-aligned version before business transformation begins."},
    {"number": 5, "slug": "step-05-explore-transform-logic", "title": "Explore data & explain transformation logic", "subtext": "This step is where the analyst studies the profiled source data and explains why transformation is needed. There may not be many helper functions here today, but future functions could support standard EDA, AI assisted analysis, and documentation of business assumptions before the logic becomes part of the repeatable pipeline."},
    {"number": "6A", "slug": "step-06a-transformation-logic", "title": "Write transformation logic", "subtext": "This step contains the main transformation logic that converts source-aligned data into the target output. Functions here support reusable pipeline code so the same logic can run consistently during development, testing, and scheduled refresh."},
    {"number": "6B", "slug": "step-06b-runtime-standards", "title": "Apply runtime audit columns inline", "subtext": "This step uses build_runtime_audit_fields for notebook/user context and adds lightweight dataframe audit columns inline: run ID, pipeline name, environment, source table, load timestamp, notebook name, and loaded-by context. Hashes, datetime features, and buckets are specialized patterns outside the default audit path."},
    {"number": "6C", "slug": "step-06c-pipeline-controls", "title": "Enforce pipeline controls", "subtext": "This step enforces the controls that decide whether the pipeline output should be trusted. Functions here support data quality rules, schema checks, classification checks, and other approved metadata validations before data is released downstream."},
    {"number": "6D", "slug": "step-06d-controlled-outputs", "title": "Write controlled outputs", "subtext": "This step writes the transformed output to the correct lakehouse, warehouse, or product layer. Functions here make the write pattern explicit, repeatable, and aligned to the intended environment instead of relying on ad hoc exports."},
    {"number": 7, "slug": "step-07-output-profile-product-contract", "title": "Profile output & publish handover metadata", "subtext": "This step profiles the created output and stores handover metadata for downstream users. Functions here record what was produced, write evidence to metadata tables or catalogues, and keep outputs understandable and reusable downstream."},
    {"number": 8, "slug": "step-08-ai-assisted-dq-suggestions", "title": "Suggest AI assisted data quality rules", "subtext": "This step uses AI in exploration notebooks to suggest possible data quality rules from profiling results, business context, and source knowledge. These AI functions are only advisory. The actual rule creation, approval, and enforcement must still be done by the human engineer in the pipeline notebook."},
    {"number": 9, "slug": "step-09-ai-assisted-classification", "title": "Suggest AI assisted column classification", "subtext": "This step uses AI in exploration notebooks to suggest column classifications such as PII, sensitivity level, and governance labels for the planned output. These AI functions are only advisory. The actual label assignment must be approved by governance or data stewards and enforced by the human engineer in the pipeline notebook."},
    {"number": 10, "slug": "step-10-lineage-handover-documentation", "title": "Generate lineage & handover documentation", "subtext": "This step creates the final documentation needed for review, handover, and future maintenance. Functions here support lineage, transformation summaries, and handover notes so another analyst or engineer can understand what was built, why it was built, and how to operate it."},
]

PUBLIC_SYMBOL_DOCS: list[PublicSymbolDocMetadata] = [{'symbol_name': 'setup_notebook',
  'module': 'config',
  'kind': 'function',
  'template_notebook': '—',
  'template_segment': '—',
  'role': 'essential',
  'summary_override': None},
 {'symbol_name': 'widget_select_agreement',
  'module': 'data_agreement',
  'kind': 'function',
  'template_notebook': '—',
  'template_segment': '—',
  'role': 'essential',
  'summary_override': 'Render a searchable agreement selector and store selected agreement metadata row in module state.'},
 {'symbol_name': 'get_selected_agreement',
  'module': 'data_agreement',
  'kind': 'function',
  'template_notebook': '—',
  'template_segment': '—',
  'role': 'essential',
  'summary_override': None},
 {'symbol_name': 'widget_render_agreement_intake_app',
  'module': 'data_agreement',
  'kind': 'function',
  'template_notebook': '`01_da_<agreement>`',
  'template_segment': 'Segment 1: Option A compact app',
  'role': 'essential',
  'summary_override': 'Render and wire the compact agreement-intake section switcher application.'},
 {'symbol_name': 'widget_render_agreement_evidence',
  'module': 'data_agreement',
  'kind': 'function',
  'template_notebook': '`01_da_<agreement>`',
  'template_segment': 'Segment 2: Option B separate widgets',
  'role': 'essential',
  'summary_override': 'Render standalone agreement evidence upload controls for an existing agreement version.'},
 {'symbol_name': 'setup_data_agreement_tables',
  'module': 'data_agreement',
  'kind': 'function',
  'template_notebook': '`00_env_config`',
  'template_segment': 'Environment and metadata bootstrap',
  'role': 'essential',
  'summary_override': 'Create, validate, and report readiness for agreement metadata tables.'},
 {'symbol_name': 'widget_render_data_agreement',
  'module': 'data_agreement',
  'kind': 'function',
  'template_notebook': '`01_da_<agreement>`',
  'template_segment': 'Segment 2: Option B separate widgets',
  'role': 'essential',
  'summary_override': 'Render append-only agreement maintenance using active steward rows.'},
 {'symbol_name': 'widget_render_data_steward',
  'module': 'data_agreement',
  'kind': 'function',
  'template_notebook': '`01_da_<agreement>`',
  'template_segment': 'Segment 2: Option B separate widgets',
  'role': 'essential',
  'summary_override': 'Render append-only data steward maintenance.'},
 {'symbol_name': 'build_runtime_audit_fields',
  'module': 'metadata',
  'kind': 'function',
  'template_notebook': '—',
  'template_segment': '—',
  'role': 'essential',
  'summary_override': 'Build shared runtime audit values; 03_pc uses notebook and committed-by context while adding dataframe audit columns inline.'},
 {'symbol_name': 'get_notebook_registry_schema',
  'module': 'metadata',
  'kind': 'function',
  'template_notebook': '—',
  'template_segment': '—',
  'role': 'optional',
  'summary_override': 'Return the required notebook registry metadata columns.'},
 {'symbol_name': 'setup_notebook_registry_table',
  'module': 'metadata',
  'kind': 'function',
  'template_notebook': '`00_env_config`',
  'template_segment': 'Metadata bootstrap',
  'role': 'essential',
  'summary_override': 'Create or validate notebook registry metadata before workflow notebooks register themselves.'},
 {'symbol_name': 'register_current_notebook',
  'module': 'metadata',
  'kind': 'function',
  'template_notebook': '—',
  'template_segment': '—',
  'role': 'essential',
  'summary_override': 'Register current notebook metadata evidence for agreement traceability.'},
 {'symbol_name': 'load_notebook_registry',
  'module': 'metadata',
  'kind': 'function',
  'template_notebook': '—',
  'template_segment': '—',
  'role': 'essential',
  'summary_override': 'Load notebook registration metadata rows for agreement notebook traceability.'},
 {'symbol_name': 'current_notebook_active_registrations',
  'module': 'metadata',
  'kind': 'function',
  'template_notebook': '—',
  'template_segment': '—',
  'role': 'optional',
  'summary_override': 'Return active latest agreement registrations for the running notebook.'},
 {'symbol_name': 'read_lakehouse_table',
  'module': 'fabric_input_output',
  'kind': 'function',
  'template_notebook': '—',
  'template_segment': '—',
  'role': 'essential',
  'summary_override': None},
 {'symbol_name': 'write_lakehouse_table',
  'module': 'fabric_input_output',
  'kind': 'function',
  'template_notebook': '—',
  'template_segment': '—',
  'role': 'essential',
  'summary_override': None},
 {'symbol_name': 'read_warehouse_table',
  'module': 'fabric_input_output',
  'kind': 'function',
  'template_notebook': '—',
  'template_segment': '—',
  'role': 'essential',
  'summary_override': None},
 {'symbol_name': 'write_warehouse_table',
  'module': 'fabric_input_output',
  'kind': 'function',
  'template_notebook': '—',
  'template_segment': '—',
  'role': 'essential',
  'summary_override': None},
 {'symbol_name': 'profile_dataframe',
  'module': 'data_profiling',
  'kind': 'function',
  'template_notebook': '—',
  'template_segment': '—',
  'role': 'essential',
  'summary_override': None},
 {'symbol_name': 'draft_business_context',
  'module': 'business_context',
  'kind': 'function',
  'template_notebook': '—',
  'template_segment': '—',
  'role': 'essential',
  'summary_override': None},
 {'symbol_name': 'prepare_business_context_profile_input',
  'module': 'business_context',
  'kind': 'function',
  'template_notebook': '—',
  'template_segment': '—',
  'role': 'optional',
  'summary_override': None},
 {'symbol_name': 'extract_column_business_context_suggestions',
  'module': 'business_context',
  'kind': 'function',
  'template_notebook': '—',
  'template_segment': '—',
  'role': 'optional',
  'summary_override': None},
 {'symbol_name': 'widget_review_business_context',
  'module': 'business_context',
  'kind': 'function',
  'template_notebook': '—',
  'template_segment': '—',
  'role': 'essential',
  'summary_override': None},
 {'symbol_name': 'get_reviewed_business_context_rows',
  'module': 'business_context',
  'kind': 'function',
  'template_notebook': '—',
  'template_segment': '—',
  'role': 'optional',
  'summary_override': None},
 {'symbol_name': 'write_business_context',
  'module': 'business_context',
  'kind': 'function',
  'template_notebook': '—',
  'template_segment': '—',
  'role': 'essential',
  'summary_override': None},
 {'symbol_name': 'draft_dq_rules',
  'module': 'data_quality',
  'kind': 'function',
  'template_notebook': '—',
  'template_segment': '—',
  'role': 'essential',
  'summary_override': None},
 {'symbol_name': 'widget_review_dq_rules',
  'module': 'data_quality',
  'kind': 'function',
  'template_notebook': '—',
  'template_segment': '—',
  'role': 'essential',
  'summary_override': None},
 {'symbol_name': 'get_dq_review_results',
  'module': 'data_quality',
  'kind': 'function',
  'template_notebook': '—',
  'template_segment': '—',
  'role': 'essential',
  'summary_override': None},
 {'symbol_name': 'write_dq_rules',
  'module': 'data_quality',
  'kind': 'function',
  'template_notebook': '—',
  'template_segment': '—',
  'role': 'essential',
  'summary_override': None},
 {'symbol_name': 'load_dq_rules',
  'module': 'data_quality',
  'kind': 'function',
  'template_notebook': '—',
  'template_segment': '—',
  'role': 'essential',
  'summary_override': None},
 {'symbol_name': 'enforce_dq',
  'module': 'data_quality',
  'kind': 'function',
  'template_notebook': '—',
  'template_segment': '—',
  'role': 'essential',
  'summary_override': None},
 {'symbol_name': 'assert_dq_passed',
  'module': 'data_quality',
  'kind': 'function',
  'template_notebook': '—',
  'template_segment': '—',
  'role': 'essential',
  'summary_override': None},
 {'symbol_name': 'draft_governance',
  'module': 'data_governance',
  'kind': 'function',
  'template_notebook': '—',
  'template_segment': '—',
  'role': 'essential',
  'summary_override': None},
 {'symbol_name': 'prepare_governance_input',
  'module': 'data_governance',
  'kind': 'function',
  'template_notebook': '—',
  'template_segment': '—',
  'role': 'optional',
  'summary_override': None},
 {'symbol_name': 'extract_governance_suggestions',
  'module': 'data_governance',
  'kind': 'function',
  'template_notebook': '—',
  'template_segment': '—',
  'role': 'optional',
  'summary_override': None},
 {'symbol_name': 'widget_review_governance',
  'module': 'data_governance',
  'kind': 'function',
  'template_notebook': '—',
  'template_segment': '—',
  'role': 'essential',
  'summary_override': None},
 {'symbol_name': 'write_governance',
  'module': 'data_governance',
  'kind': 'function',
  'template_notebook': '—',
  'template_segment': '—',
  'role': 'essential',
  'summary_override': None},
 {'symbol_name': 'load_governance',
  'module': 'data_governance',
  'kind': 'function',
  'template_notebook': '—',
  'template_segment': '—',
  'role': 'essential',
  'summary_override': None},
 {'symbol_name': 'build_lineage_records',
  'module': 'data_lineage',
  'kind': 'function',
  'template_notebook': '—',
  'template_segment': '—',
  'role': 'essential',
  'summary_override': None},
 {'symbol_name': 'build_lineage_handover_markdown',
  'module': 'data_lineage',
  'kind': 'function',
  'template_notebook': '—',
  'template_segment': '—',
  'role': 'essential',
  'summary_override': None},
 {'symbol_name': 'build_handover',
  'module': 'handover',
  'kind': 'function',
  'template_notebook': '—',
  'template_segment': '—',
  'role': 'essential',
  'summary_override': None},
 {'symbol_name': 'render_handover_markdown',
  'module': 'handover',
  'kind': 'function',
  'template_notebook': '—',
  'template_segment': '—',
  'role': 'essential',
  'summary_override': None},
 {'symbol_name': 'read_lakehouse_csv',
  'module': 'fabric_input_output',
  'kind': 'function',
  'template_notebook': '—',
  'template_segment': '—',
  'role': 'optional',
  'summary_override': None},
 {'symbol_name': 'read_lakehouse_parquet',
  'module': 'fabric_input_output',
  'kind': 'function',
  'template_notebook': '—',
  'template_segment': '—',
  'role': 'optional',
  'summary_override': None},
 {'symbol_name': 'read_lakehouse_excel',
  'module': 'fabric_input_output',
  'kind': 'function',
  'template_notebook': '—',
  'template_segment': '—',
  'role': 'optional',
  'summary_override': 'Read an Excel file from a Fabric lakehouse Files path and pass options such as skiprows, header, usecols, dtype, and nrows through to pandas.read_excel.'},
 {'symbol_name': 'validate_dq_rules',
  'module': 'data_quality',
  'kind': 'function',
  'template_notebook': '—',
  'template_segment': '—',
  'role': 'optional',
  'summary_override': None},
 {'symbol_name': 'widget_review_dq_rule_deactivations',
  'module': 'data_quality',
  'kind': 'function',
  'template_notebook': '—',
  'template_segment': '—',
  'role': 'optional',
  'summary_override': None},
 {'symbol_name': 'validate_schema',
  'module': 'drift',
  'kind': 'function',
  'template_notebook': '03_pc_<agreement>_<pipeline>',
  'template_segment': 'Preset schema checks',
  'role': 'essential',
  'summary_override': 'Validate a dataframe schema using strict, allow_new_columns, or monitor_only presets.'},
 {'symbol_name': 'monitor_data_changes',
  'module': 'drift',
  'kind': 'function',
  'template_notebook': '03_pc_<agreement>_<pipeline>',
  'template_segment': 'Preset data-change monitoring',
  'role': 'essential',
  'summary_override': 'Profile a dataframe, select the appropriate baseline, compare distributions, and return a data-change result from a preset.'},
 {'symbol_name': 'stop_if_failed',
  'module': 'drift',
  'kind': 'function',
  'template_notebook': '03_pc_<agreement>_<pipeline>',
  'template_segment': 'Preset guardrail enforcement',
  'role': 'essential',
  'summary_override': 'Raise the shared guardrail error only when a schema or data-change result cannot continue.'},
 {'symbol_name': 'get_package_version',
  'module': 'versioning',
  'kind': 'function',
  'template_notebook': '`00_env_config`',
  'template_segment': 'Segment 1: Explain the shared environment role',
  'role': 'optional',
  'summary_override': 'Return the installed FabricOps Starter Kit package version for the active notebook runtime.'},
 {'symbol_name': 'get_docs_version',
  'module': 'versioning',
  'kind': 'function',
  'template_notebook': '`00_env_config`',
  'template_segment': 'Segment 1: Explain the shared environment role',
  'role': 'optional',
  'summary_override': 'Map a full package version to the matching major.minor documentation version.'},
 {'symbol_name': 'get_docs_url',
  'module': 'versioning',
  'kind': 'function',
  'template_notebook': '`00_env_config`',
  'template_segment': 'Segment 1: Explain the shared environment role',
  'role': 'optional',
  'summary_override': 'Return the published documentation URL for a package version.'},
 {'symbol_name': 'get_release_notes_url',
  'module': 'versioning',
  'kind': 'function',
  'template_notebook': '`00_env_config`',
  'template_segment': 'Segment 1: Explain the shared environment role',
  'role': 'optional',
  'summary_override': 'Return the patch-specific release notes URL for a package version.'},
 {'symbol_name': 'print_runtime_banner',
  'module': 'versioning',
  'kind': 'function',
  'template_notebook': '`00_env_config`',
  'template_segment': 'Segment 1: Explain the shared environment role',
  'role': 'essential',
  'summary_override': 'Print the installed package version and matching documentation links in a notebook-friendly banner.'},
 {'symbol_name': 'FabricStore',
  'module': 'fabric_input_output',
  'kind': 'class',
  'template_notebook': '—',
  'template_segment': '—',
  'role': 'optional',
  'summary_override': None}]
