"""Supported public API contract for release-facing notebook functions."""

SUPPORTED_PUBLIC_API = (
    "fabricops_kit.config.setup_metadata_tables",
    "fabricops_kit.config.setup_notebook",
    "fabricops_kit.data_agreement.widget_render_agreement_evidence",
    "fabricops_kit.data_agreement.widget_render_data_agreement",
    "fabricops_kit.data_agreement.widget_render_data_steward",
    "fabricops_kit.data_profiling.profile_dataframe",
    "fabricops_kit.fabric_input_output.read_lakehouse_csv",
    "fabricops_kit.fabric_input_output.read_lakehouse_excel",
    "fabricops_kit.fabric_input_output.read_lakehouse_parquet",
    "fabricops_kit.fabric_input_output.read_lakehouse_table",
    "fabricops_kit.fabric_input_output.read_warehouse_query",
    "fabricops_kit.fabric_input_output.read_warehouse_table",
    "fabricops_kit.fabric_input_output.write_lakehouse_table",
    "fabricops_kit.fabric_input_output.write_warehouse_table",
    "fabricops_kit.governance_review.get_latest_metadata_catalogue",
    "fabricops_kit.governance_review.widget_author_dq_rules",
    "fabricops_kit.governance_review.widget_author_schema_freshness_profile_rules",
    "fabricops_kit.governance_review.widget_enrich_table_metadata",
    "fabricops_kit.governance_review.widget_review_guardrail_governance",
    "fabricops_kit.governance_review.widget_select_guardrail_target",
    "fabricops_kit.pipeline.display_guardrail_results",
    "fabricops_kit.pipeline.prepare_pipeline_table_configs",
    "fabricops_kit.pipeline.run_table_guardrails",
    "fabricops_kit.pipeline.start_pipeline_run",
    "fabricops_kit.pipeline.write_pipeline_lineage",
    "fabricops_kit.pipeline.write_pipeline_run_summary",
)
