"""Supported public API contract for release-facing notebook functions."""

SUPPORTED_PUBLIC_API = (
    "fabricops_kit.config.setup_metadata_tables.setup_metadata_tables",
    "fabricops_kit.config.setup_notebook.setup_notebook",
    "fabricops_kit.widgets.widget_render_agreement_evidence.widget_render_agreement_evidence",
    "fabricops_kit.widgets.widget_render_data_agreement.widget_render_data_agreement",
    "fabricops_kit.widgets.widget_render_data_steward.widget_render_data_steward",
    "fabricops_kit.pipeline.profile_dataframe",
    "fabricops_kit.io.read_lakehouse_csv.read_lakehouse_csv",
    "fabricops_kit.io.read_lakehouse_excel.read_lakehouse_excel",
    "fabricops_kit.io.read_lakehouse_parquet.read_lakehouse_parquet",
    "fabricops_kit.io.read_lakehouse_table.read_lakehouse_table",
    "fabricops_kit.io.read_warehouse_query.read_warehouse_query",
    "fabricops_kit.io.read_warehouse_table.read_warehouse_table",
    "fabricops_kit.io.write_lakehouse_table.write_lakehouse_table",
    "fabricops_kit.io.write_warehouse_table.write_warehouse_table",
    "fabricops_kit.widgets.widget_browse_metadata_catalogue.widget_browse_metadata_catalogue",
    "fabricops_kit.widgets.widget_author_dq_rules.widget_author_dq_rules",
    "fabricops_kit.widgets.widget_author_schema_freshness_profile_rules.widget_author_schema_freshness_profile_rules",
    "fabricops_kit.widgets.widget_enrich_table_metadata.widget_enrich_table_metadata",
    "fabricops_kit.widgets.widget_review_guardrail_governance.widget_review_guardrail_governance",
    "fabricops_kit.widgets.widget_select_guardrail_target.widget_select_guardrail_target",
    "fabricops_kit.pipeline.display_guardrail_results",
    "fabricops_kit.pipeline.prepare_pipeline_table_configs",
    "fabricops_kit.pipeline.run_table_guardrails",
    "fabricops_kit.widgets.widget_pipeline_bootstrap.widget_pipeline_bootstrap",
    "fabricops_kit.pipeline.write_pipeline_lineage",
    "fabricops_kit.pipeline.write_pipeline_run_summary",
)
