"""Call Graph Data job ownership module."""

from __future__ import annotations

from . import shared as _shared

generate_function_call_graph_artifacts = _shared.generate_function_call_graph_artifacts
_build_callable_flow_data = _shared._build_callable_flow_data
_build_function_inventory = _shared._build_function_inventory
_build_public_entrypoint_flow = _shared._build_public_entrypoint_flow
_collect_call_graph_generation_inputs = _shared._collect_call_graph_generation_inputs

FUNCTION_CALL_GRAPH_DATA_PATH = _shared.FUNCTION_CALL_GRAPH_DATA_PATH
FUNCTION_CALL_GRAPH_DASHBOARD_PATH = _shared.FUNCTION_CALL_GRAPH_DASHBOARD_PATH
