import type {ReactNode} from 'react';
import {AbsoluteFill,Easing,Sequence,interpolate,spring,useCurrentFrame,useVideoConfig} from 'remotion';
import {NotebookCapture,WidgetCapture,CodeCapture} from '../components/ProductCapture';
import {FabricIconCard,SELECTED_FABRIC_ICONS} from '../components/FabricIcons';
import {DataContract,StatusBadge} from '../components/Primitives';
import {ProductStory} from './ProductStory';
import {theme} from '../theme';

const ease=(f:number,a:number,b:number)=>interpolate(f,[a,b],[0,1],{extrapolateLeft:'clamp',extrapolateRight:'clamp',easing:Easing.inOut(Easing.cubic)});
const ChapterFade=({duration,children}:{duration:number;children:ReactNode})=>{const frame=useCurrentFrame(),opacity=interpolate(frame,[0,24,duration-24,duration],[0,1,1,0],{extrapolateLeft:'clamp',extrapolateRight:'clamp'});return <AbsoluteFill style={{opacity}}>{children}</AbsoluteFill>;};
const Chapter=({from,duration,children}:{from:number;duration:number;children:ReactNode})=><Sequence from={from} durationInFrames={duration}><ChapterFade duration={duration}>{children}</ChapterFade></Sequence>;
const Kinetic=({text,at=20,color=theme.text,x=120,y=90,size=28}:{text:string;at?:number;color?:string;x?:number;y?:number;size?:number})=>{const f=useCurrentFrame(),p=spring({frame:f-at,fps:30,config:{damping:18,stiffness:110}});return <div style={{position:'absolute',left:x,top:y,color,fontSize:size,fontWeight:760,opacity:p,clipPath:`inset(0 ${100-p*100}% 0 0)`,transform:`translateY(${(1-p)*18}px)`}}>{text}</div>;};
const CaptureChapter=({kind,title,placeholder,accent,beats,stepFrames=270}:{kind:'notebook'|'widget'|'code';title:string;placeholder:string;accent:string;beats:string[];stepFrames?:number})=>{const f=useCurrentFrame(),Capture=kind==='widget'?WidgetCapture:kind==='code'?CodeCapture:NotebookCapture,step=Math.min(beats.length-1,Math.floor(f/stepFrames)),pulse=ease(f%stepFrames,25,65);return <AbsoluteFill><Capture title={title} placeholder={placeholder} accent={accent} zoom={1.03} panX={-18} panY={-8} highlight={{x:180+step*135,y:155+step*70,width:420,height:120,label:beats[step]}}/><div style={{position:'absolute',left:210,bottom:75,display:'flex',gap:12}}>{beats.map((beat,i)=><div key={beat} style={{padding:'10px 15px',borderRadius:99,border:`1px solid ${i===step?accent:'#53637a55'}`,color:i===step?accent:'#718198',background:i===step?`${accent}18`:'#091425',transform:`scale(${i===step?1+pulse*.06:1})`}}>{beat}</div>)}</div></AbsoluteFill>;};
const OperatingModel=()=>{const f=useCurrentFrame(),stages=['Prepare','Configure','Govern','Engineer','Validate','Activate','Production','Consume'],colors=[theme.neutral,theme.neutral,theme.governance,theme.engineering,theme.engineering,theme.governance,theme.production,theme.consumer];return <AbsoluteFill><Kinetic text="A repeatable operating practice" at={25} x={690} y={100} size={34}/><div style={{position:'absolute',left:105,top:310,display:'flex',gap:20}}>{stages.map((s,i)=>{const p=spring({frame:f-80-i*42,fps:30,config:{damping:18,stiffness:100}});return <div key={s} style={{width:185,height:105,display:'grid',placeItems:'center',borderRadius:20,border:`1px solid ${colors[i]}88`,background:`${colors[i]}18`,color:colors[i],fontSize:19,fontWeight:700,opacity:p,transform:`translateY(${(1-p)*35}px)`}}>{s}{i<stages.length-1&&<span style={{position:'absolute',marginLeft:205,color:'#5f7189'}}>→</span>}</div>})}</div><div style={{position:'absolute',left:300,top:590,display:'flex',gap:30}}>{[['Governance',theme.governance],['Engineering Development',theme.engineering],['Engineering Production',theme.production],['Consumer',theme.consumer]].map(([label,color],i)=><div key={label} style={{width:300,padding:'26px 20px',borderRadius:24,border:`1px solid ${color}77`,background:`${color}14`,opacity:ease(f,430+i*55,480+i*55),transform:`translateY(${(1-ease(f,430+i*55,480+i*55))*30}px)`}}><FabricIconCard {...SELECTED_FABRIC_ICONS.workspace} style={{margin:'auto'}}/><div style={{color,textAlign:'center',fontWeight:720,marginTop:12}}>{label}</div></div>)}</div></AbsoluteFill>;};
const ContractLoop=()=>{const f=useCurrentFrame(),go=ease(f,45,145),run=ease(f,180,300),back=ease(f,330,450),pass=ease(f,500,590);return <AbsoluteFill><Kinetic text="Data Contract validation loop" at={15} x={720} y={85} size={34}/><div style={{position:'absolute',left:250,top:340,color:theme.governance,fontSize:26,fontWeight:750}}>Governance authors intent</div><div style={{position:'absolute',left:1370,top:340,color:theme.engineering,fontSize:26,fontWeight:750}}>Engineering validates</div><div style={{position:'absolute',left:841,top:405,transform:`scale(${.9+go*.1})`}}><DataContract active={pass>.7}/></div><svg width="1920" height="1080" style={{position:'absolute',inset:0}}><path d="M 560 430 C 700 280 790 330 841 480" fill="none" stroke={theme.governance} strokeWidth="4" pathLength="1" strokeDasharray="1" strokeDashoffset={1-go}/><path d="M 1079 480 C 1170 330 1300 300 1430 430" fill="none" stroke={theme.engineering} strokeWidth="4" pathLength="1" strokeDasharray="1" strokeDashoffset={1-run}/><path d="M 1430 610 C 1240 790 760 790 560 610" fill="none" stroke={back>.9?theme.production:theme.engineering} strokeWidth="4" pathLength="1" strokeDasharray="1" strokeDashoffset={1-back}/></svg><Kinetic text="Freeze expectations" at={60} x={300} y={490} color={theme.governance}/><Kinetic text="Run ETL + Guardrails" at={210} x={1350} y={490} color={theme.engineering}/><Kinetic text="Refine and repeat" at={350} x={830} y={790} color="#b7c5d7"/><div style={{position:'absolute',left:900,top:620,opacity:pass}}><StatusBadge label="VALIDATED"/></div></AbsoluteFill>;};
const Promotion=()=>{const f=useCurrentFrame(),activate=ease(f,50,150),move=ease(f,240,480);return <AbsoluteFill><Kinetic text="Activate" at={30} x={510} y={120} color={theme.governance} size={36}/><Kinetic text="Promote" at={220} x={1260} y={120} color={theme.production} size={36}/><div style={{position:'absolute',left:250,top:300,width:580,height:520,border:`1px solid ${theme.engineering}88`,borderRadius:30,background:`${theme.engineering}12`}}><Kinetic text="Engineering Development" at={20} x={55} y={40} color={theme.engineering}/></div><div style={{position:'absolute',left:1090,top:300,width:580,height:520,border:`1px solid ${theme.production}88`,borderRadius:30,background:`${theme.production}12`}}><Kinetic text="Engineering Production" at={210} x={55} y={40} color={theme.production}/></div><div style={{position:'absolute',left:390+move*835,top:540,transform:`scale(${1-move*.08})`,padding:'25px 35px',borderRadius:18,border:`2px solid ${move>.8?theme.production:theme.engineering}`,background:'#101d31',color:'#fff',fontSize:24,fontWeight:750}}>02_pipeline</div><div style={{position:'absolute',left:840,top:350,opacity:activate}}><StatusBadge label="ACTIVE CONTRACT"/></div></AbsoluteFill>;};
const ConsumerFlow=()=>{const f=useCurrentFrame(),flow=ease(f,100,320);return <AbsoluteFill><Kinetic text="Approved Production data" at={20} x={725} y={90} color={theme.production} size={34}/><div style={{position:'absolute',left:220,top:360,width:420,height:270,border:`1px solid ${theme.production}`,borderRadius:28,display:'grid',placeItems:'center',color:theme.production,fontSize:25}}>Engineering Production</div><svg width="1920" height="1080" style={{position:'absolute',inset:0}}><path d="M 640 495 C 850 495 890 495 1080 495" fill="none" stroke={theme.production} strokeWidth="5" pathLength="1" strokeDasharray="1" strokeDashoffset={1-flow}/></svg><div style={{position:'absolute',left:1080,top:280,width:620,height:430,border:`1px solid ${theme.consumer}`,borderRadius:28,background:`${theme.consumer}10`,opacity:flow}}><Kinetic text="Consumer Workspace" at={250} x={190} y={35} color={theme.consumer}/>{['99_explore','Power BI','AI / machine learning','Data Science'].map((x,i)=><div key={x} style={{position:'absolute',left:70+(i%2)*275,top:130+Math.floor(i/2)*120,color:'#f5dcc0',opacity:ease(f,320+i*55,360+i*55),fontSize:20}}>{x}</div>)}</div><Kinetic text="Production only" at={470} x={815} y={750} color={theme.production}/></AbsoluteFill>;};
const Architecture=()=>{const f=useCurrentFrame(),p=ease(f,30,170);return <AbsoluteFill style={{transform:`scale(${1.15-p*.15})`}}><Kinetic text="One operating model" at={20} x={760} y={80} size={38}/><div style={{position:'absolute',left:710,top:220,width:500,padding:35,border:`1px solid ${theme.governance}`,borderRadius:28,textAlign:'center',color:theme.governance,fontSize:25}}>Governance<br/><span style={{fontSize:16}}>metadata + active Data Contract</span></div><div style={{position:'absolute',left:100,top:570,width:480,padding:35,border:`1px solid ${theme.engineering}`,borderRadius:28,textAlign:'center',color:theme.engineering,fontSize:24}}>Engineering Development</div><div style={{position:'absolute',left:720,top:570,width:480,padding:35,border:`1px solid ${theme.production}`,borderRadius:28,textAlign:'center',color:theme.production,fontSize:24}}>Engineering Production</div><div style={{position:'absolute',left:1340,top:570,width:480,padding:35,border:`1px solid ${theme.consumer}`,borderRadius:28,textAlign:'center',color:theme.consumer,fontSize:24}}>Consumer</div><svg width="1920" height="1080" style={{position:'absolute',inset:0}}><path d="M 960 340 V 500 M 580 620 H 720 M 1200 620 H 1340" stroke="#b9c7d8" strokeWidth="4" fill="none" pathLength="1" strokeDasharray="1" strokeDashoffset={1-p}/></svg><div style={{position:'absolute',left:590,top:850,display:'flex',gap:18}}>{['Code-first','Config-driven','Governance-as-Code','Repeatable'].map((x,i)=><span key={x} style={{padding:'10px 15px',border:'1px solid #71839b77',borderRadius:99,color:'#b9c7d8',opacity:ease(f,260+i*45,300+i*45)}}>{x}</span>)}</div></AbsoluteFill>;};
const CTA=()=>{const f=useCurrentFrame(),a=ease(f,100,150)*(1-ease(f,240,280)),b=ease(f,270,320)*(1-ease(f,410,450));return <AbsoluteFill style={{display:'flex',alignItems:'center',justifyContent:'center',flexDirection:'column'}}><div style={{fontSize:100,fontWeight:800}}>Fabric<span style={{color:theme.production}}>Ops</span></div><div style={{fontSize:21,color:theme.muted,marginTop:20}}>Lightweight. Self-contained. Built for Microsoft Fabric.</div><div style={{display:'flex',gap:24,marginTop:60}}>{[['How FabricOps works',a],['Guided Demo',b]].map(([x,p],i)=><div key={String(x)} style={{padding:'17px 28px',borderRadius:99,border:`1px solid ${i?theme.production:'#7890ad'}`,color:i?theme.production:'#e4ecf6',transform:`scale(${1+Number(p)*.14})`,boxShadow:`0 0 ${Number(p)*35}px ${i?theme.production:'#71adff'}66`}}>{x} →</div>)}</div></AbsoluteFill>;};

export const LongFormStory=()=> <AbsoluteFill>
 <Chapter from={0} duration={1350}><ProductStory openingOnly/></Chapter>
 <Chapter from={1290} duration={1410}><OperatingModel/></Chapter>
 <Chapter from={2640} duration={1200}><CaptureChapter kind="notebook" title="00_env_config · Microsoft Fabric" placeholder="PLACEHOLDER — capture 00_env_config in Governance workspace" accent={theme.neutral} stepFrames={360} beats={['Config-driven','Object paths','Same workflow · different environment']}/></Chapter>
 <Chapter from={3780} duration={2100}><CaptureChapter kind="widget" title="01_governance · Data Contract authoring" placeholder="PLACEHOLDER — record widget_author_data_contract for Orders table_id" accent={theme.governance} stepFrames={480} beats={['Select table_id','Enrich','Define Guardrails','Freeze Contract']}/></Chapter>
 <Chapter from={5820} duration={1800}><CaptureChapter kind="code" title="02_pipeline · Engineering Development" placeholder="PLACEHOLDER — record 02_pipeline profiling and Guardrail validation" accent={theme.engineering} stepFrames={420} beats={['Read & Profile','Transform & Audit','Validate Guardrails','Write']}/></Chapter>
 <Chapter from={7200} duration={1050}><ContractLoop/></Chapter>
 <Chapter from={8190} duration={1200}><Promotion/></Chapter>
 <Chapter from={9330} duration={750}><CaptureChapter kind="code" title="02_pipeline · Engineering Production" placeholder="PLACEHOLDER — record Production 02_pipeline run" accent={theme.production} stepFrames={220} beats={['Resolve active contract','Governed ETL','Approved write']}/></Chapter>
 <Chapter from={10020} duration={900}><><CaptureChapter kind="notebook" title="99_explore · Consumer" placeholder="PLACEHOLDER — record 99_explore reading approved Production data" accent={theme.consumer} beats={['Read-only exploration','Approved data']}/><ConsumerFlow/></></Chapter>
 <Chapter from={10860} duration={750}><Architecture/></Chapter>
 <Chapter from={11550} duration={600}><CTA/></Chapter>
 </AbsoluteFill>;
